dist: trusty
group: trusty_lts
sudo: required
language:
    - cpp
compiler:
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - gcc-7
before_install:
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      #- sudo apt-get update -qq
    - sudo apt-get install -y libwxgtk3.0-dev libgtk2.0-dev gettext libasound2-dev alsa-utils alsa-oss
    - git show -s --format="#define REV_LONG \"%H\"%n#define REV_TIME \"%cd\"%n" | tee ./src/RevisionIdent.h
    - export CXX="/usr/bin/g++-7" CC="/usr/bin/gcc-7"
    - FLAGS="-w -std=gnu++11"
    - export CFLAGS="$CFLAGS $FLAGS"
    - export CXXFLAGS="$CXXFLAGS $FLAGS"
    - gcc --version && g++ --version
script:
    -  time ./configure && time make -j2
